### ISSUE TITLE
EB01: Duplicate track descriptions?

### ISSUE THREAD

**Issue by noelleleigh** [orllewin/orllewin.github.io#2]
Are the track descriptions for "05 kurakkusu: noisefuel" and "06 untitled (wind): tom hackshaw" meant to be identical?

https://github.com/orllewin/orllewin.github.io/blob/3decc45f4b9964596d72a50402ea3d1d2a4449b5/elmet_brae/EB01/index.html#L65

https://github.com/orllewin/orllewin.github.io/blob/3decc45f4b9964596d72a50402ea3d1d2a4449b5/elmet_brae/EB01/index.html#L72

**Comment by orllewin** [comment]
How did I not notice that.... fixed, thank you
